### PR TITLE
Enhance subscribe and channels 

### PR DESCRIPTION
**Pull request by bangxiangyong**
Previously, we had a pseudo-subscribe, that is information of the channel was provided in the message. 
But not an actual subscription to channel - the agents are still receiving messages from all channels but 'choose' not to handle them in the `on_received_message`. 

Now, clear separation of channels is implemented and receiving end will not receive unintended messages from channels they have not subscribed to.

UPDATE: Ability to display names of edges. This is possible with the information of specific channels defined in this pull RQ.
By default, "default" channel name is not displayed (see below), however this can be switched via:
`agentNetwork = AgentNetwork(hide_default_edge=False)`
image

### CODE REVIEW

**Comment by bangxiangyong** [comment]
One required implementation on the dashboard will be specifying the specific channels to subscribe to.

**Comment by bangxiangyong** [comment]
Ah, these commits failed the circleci checks. I'll need to update the test suite to include the binding with specifying the correct channels

**Comment by BjoernLudwigPTB** [comment]
PS: regarding the occasional pipeline fails with timeout errors, I would suggest to merge `develop` into this one here, because it contains the respective fix.

**Comment by bangxiangyong** [comment]
The latest updates from this branch has been merged into branch of `enhance_UI`  https://github.com/Met4FoF/agentMET4FOF/pull/222

Any additional updates to this branch should not be made.

**Comment by BjoernLudwigPTB** [comment]
> The latest updates from this branch has been merged into branch of `enhance_UI` #222
> 
> Any additional updates to this branch should not be made.

Nice, then we continue over there. By the way, you can at all times change the so-called base-branch of a PR and merge your changes from one PR into any branch and thus any other PR that has been opened.

**Pull request closed without merging**
